---
layout: default

---

### Publications

_Please email me for pdf copies of papers hidden behind a paywall._

#### In progress 

- Rodrigues MA, Paris M, Kapun M, **Durmaz E**, Kerdaffrec E, Flatt T. “The transcriptional underpinnings of the trade-off between reproduction and somatic maintenance in _Drosophila melanogaster_”, _pdf available upon request._ 

- Kapun M, **Durmaz E**, Kawecki T, Schmidt P, Flatt T. “An ancestrally tropical balanced inversion polymorphism confers global adaptation to warm climate”, _pdf available upon request._

#### Published 

- Rodrigues MA, Merckelbach A, **Durmaz E**, Kerdaffrec E, Flatt T. Transcriptomic evidence for a trade-off between germline proliferation and immunity in _Drosophila_, Evolution Letters, 2021; doi:10.1002/evl3.261.

- Ozsoy E, Yilmaz M, Patlar B, Emecen G, **Durmaz E**, Magwire MM, Zhou S, Anholt RRH, Mackay TFC. Epistasis for head morphology in _Drosophila melanogaster_, G3, 2021; 11:10–jkab285.

- Betancourt N, Rajpurohit S, **Durmaz E**, Fabian DK, Kapun M, Thomas F, Schmidt P. Allelic polymorphism at _foxo_ contributes to local adaptation in _Drosophila melanogaster_, Molecular Ecology, 2021; 00:1–14.

- **Durmaz E**, Kerdaffrec E, Katsianis G, Kapun M, Flatt T. How does selection act on chromosomal inversions?, eLS (Encyclopaedia of Life Sciences), 2020; 1, 307–315.

- **Durmaz E**, Rajpurohit S, Betancourt N, Fabian DK, Kapun M, Schmidt P, Thomas F. A clinal polymorphism in the insulin signaling transcription factor _foxo_ contributes to life-history adaptation in _Drosophila_, Evolution, 2019; 73-9(5):1774-1792. 

- **Durmaz E**, Benson C, Kapun M, Schmidt P, Flatt T. An inversion supergene in _Drosophila_ underpins latitudinal clines in survival traits, Journal of Evolutionary Biology, 2018; 31(9):1354-1364.

- Kapun M, Schmidt C, **Durmaz E**, Schmidt PS, Flatt T. Parallel effects of the inversion _In(3R)Payne_ on body size across the North American and Australian clines in _Drosophila melanogaster_, Journal of Evolutionary Biology, 2016; 29(5):1059-72. 

- Demirci B, **Durmaz E**, Alten B. Influence of Bloodmeal Source on Reproductive Output of the Potential West Nile Vector, _Culex theileri_ (Diptera: Culicidae), Journal of Medical Entomology, 2014, 1;51(6):1312-6.

### Presentations at Conferences / Meetings 

- **Durmaz E**, Kerdaffrec E, Flatt T. Experimental Evolution of an Adaptive Inversion Polymorphism, Evolution 2021, June 2021, USA / online – oral presentation

- Kerdaffrec E, **Durmaz E**, Katsianis G, Flatt T. Testing evolutionary forces maintaining a clinal inversion polymorphism, Evolution 2021, June 2021, USA / online – contribution, oral presentation

- **Durmaz E**, Kerdaffrec E, Flatt T. Experimental Evolution of an Adaptive Inversion Polymorphism, 62nd Annual _Drosophila_ Research Conference, March 2021, Genetic Society of America, USA / online – poster presentation

- **Durmaz E**. The DrosEU phenotyping collaboration, A community-based approach to understanding _Drosophila_ Evolution through Space and Time (DEST) Workshop, 62nd Annual _Drosophila_ Research Conference, March 2021, Genetic Society of America, USA / online – invited speaker, oral presentation

- **Durmaz E**. Patterns of Clinal adaptation in _Drosophila_, Behaviour, Ecology, Environment and Evolution Seminar, University of Zurich, March 2021, Zurich, Switzerland / online – invited speaker

- **Durmaz E**. _Drosophila_’da enlemsel klinler ve adaptasyon (in Turkish), University of Hacettepe, Department of Biology, January 2021, Ankara, Turkey / online – invited guest lecturer for Genetics

- Kerdaffrec E, **Durmaz E**, Katsianis G, Flatt T. Testing evolutionary forces maintaining a clinal inversion polymorphism, The Swiss Conference for Organismic Biology 2020, February 2020, Fribourg, Switzerland – contribution, oral presentation

- **Durmaz E**. Clinal adaptation in _Drosophila_, 14th Aykut Kence Evolution Conference, January 2020, Ankara, Turkey – invited speaker for academic session

- **Durmaz E**. Adaptasyon genetigi (in Turkish), 14th Aykut Kence Evolution Conference, January 2020, Ankara, Turkey – invited speaker for public session

- **Durmaz E**, Kerdaffrec E, Katsianis G, Flatt T. Testing evolutionary forces maintaining a clinal inversion polymorphism, European _Drosophila_ Research Conference (EDRC), September 2019, Lausanne, Switzerland – poster presentation

- Demir E, Yagli SS, **Durmaz E**, Onder BS. Seasonal immune response in a _Drosophila melanogaster_ population, The Congress of the European Society for Evolutionary Biology (ESEB), August 2019, Turku, Finland – contribution, poster presentation

- **Durmaz E**, Kerdaffrec E, Katsianis G, Flatt T. Testing evolutionary forces maintaining a clinal inversion polymorphism, The Congress of the European Society for Evolutionary Biology (ESEB), August 2019, Turku, Finland – poster presentation

- **Durmaz E**, Benson C, Kapun M, Schmidt P, Flatt T. An inversion supergene in _Drosophila_ underpins latitudinal clines in survival traits, The Swiss Conference for Organismic Biology 2019, February 2019, Zurich, Switzlerland – poster presentation

- **Durmaz E**. A clinal polymorphism at _foxo_ contributes to life-history adaptation in _Drosophila_, Society of Molecular Biology and Evolution (SMBE) Satellite Meeting, February 2019, Vienna, Austria – oral presentation (cancelled)

- **Durmaz E**. The effects of clinal polymorphisms on _Drosophila_ life history, University of Hacettepe, Department of Biology, January 2019, Ankara, Turkey / online – invited guest lecturer for Genetics

- **Durmaz E**, Benson C, Kapun M, Schmidt PS, Thomas F. A clinal inversion in _Drosophila_ represents a life-history supergene, II Joint Congress on Evolutionary Biology, August 2018, Montpellier, France – poster presentation

- **Durmaz E**, Benson C, Kapun M, Schmidt PS, Thomas F. A clinal inversion in _Drosophila_ represents a life-history supergene, Ecology and Evolutionary Biology Symposium, July 2018, Izmir, Turkey – oral presentation

- **Durmaz E**, Benson C, Kapun M, Schmidt PS, Thomas F. Effects of a clinal inversion on thermal life-history reaction norms in _Drosophila melanogaster_ 16th Congress of the European Society for Evolutionary Biology (ESEB), August 2017, Groningen, Netherlands – poster presentation

- **Durmaz E**, Rajpurohit S, Betancourt N, Schmidt PS, Thomas F. A clinal polymorphism in insulin signaling has pleiotropic effects on _Drosophila_ life history Evolution Meeting, June 2016, Austin, Texas, USA – oral presentation

- **Durmaz E**, Rajpurohit S, Betancourt N, Schmidt PS, Thomas F. A clinal polymorphism in insulin signaling has major pleiotropic effects on _Drosophila_ life history The Swiss Conference for Organismic Biology 2016, February 2016, Lausanne, Switzerland – poster presentation 

- **Durmaz E**, Rajpurohit S, Betancourt N, Schmidt PS, Thomas F. A clinal polymorphism in insulin signaling has major pleiotropic effects on _Drosophila_ life history, European Society for Evolutionary Biology (ESEB) XV meeting, August 2015, Lausanne, Switzerland – oral presentation 

- **Durmaz E**, Rajpurohit S, Betancourt N, Schmidt PS, Thomas F. A clinal polymorphism in insulin signaling has major pleiotropic effects on _Drosophila_ life history, Swiss Drosophila Meeting, 2015 April, Lausanne, Switzerland – poster presentation 

- **Durmaz E**, Rajpurohit S, Betancourt N, Schmidt PS, Thomas F. Testing the Life History Effects of SNP Polymorphisms as Identified by an NGS Analysis of a Latitudinal Cline in _Drosophila_, Eukaryotic –Omics: Exploring and testing with next-generation sequencing, April 2014, Geneva, Switzerland – oral presentation

- Hiroto Kameyama H, **Durmaz E**, Hanna G, Markow T. Sperm length predicts female sperm loads in _Drosophila_ species in the wild, 54th Annual Drosophila Research Conference, April 2013 Washington, DC. USA – contribution, poster presentation

- **Durmaz E**, Ozsoy E, Markow T. The effect of mating status on environmental stress factors in genetically different natural populations of _Drosophila subobscura_ (Drosophilidae, Diptera), 21th National Congress of Biology, September 2012, Izmir, Turkey – poster presentation


[back](./)

